[package]
name = "camoflage"
description = "CAMO-compatible Image Proxy Server"
version = "0.1.0"
edition = "2021"
authors = ["CULTPONY <mail@cult.horse>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.5", features = ["http2", "headers"] }
axum-extra = { version = "0.3", features = ["typed-routing", "query"] }
base64 = "0.13.0"
bytes = "*"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.2", features = ["derive", "env"] }
duration-str = "0.3"
flexi_logger = { version = "0.22", features = ["use_chrono_for_offset"] }
hex = "0.4.3"
hmac = "0.12.1"
image = "0.24"
lazy_static = "1.4.0"
log = "0.4"
reqwest = { version = "0.11", default-features = false, features = ["stream", "rustls-tls-native-roots"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.82"
sha1 = "0.10.1"
sha3 = "0.10.1"
thiserror = "1.0.31"
tokio = { version = "1.18", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.2", features = ["full"] }
url = { version = "2.2", features = ["serde"] }

[dev-dependencies]
tokio = { version = "*", features = ["test-util"] }