[package]
name = "camoflage"
description = "CAMO-compatible Image Proxy Server"
version = "0.1.0"
edition = "2021"
author = "CULTPONY <mail@cult.horse>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
