[package]
name = "camoflage"
description = "CAMO-compatible Image Proxy Server"
version = "0.1.0"
edition = "2021"
authors = ["CULTPONY <mail@cult.horse>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6", features = ["http2", "headers"] }
axum-extra = { version = "0.7", features = ["typed-routing", "query"] }
base64 = "0.21.0"
bytes = "*"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.2", features = ["derive", "env"] }
duration-str = "0.5"
flexi_logger = { version = "0.23", features = ["use_chrono_for_offset"] }
hex = "0.4.3"
hmac = "0.12.1"
image = "0.24"
ipnetwork = "0.20.0"
lazy_static = "1.4.0"
log = "0.4"
reqwest = { version = "0.11", default-features = false, features = ["stream", "rustls-tls-native-roots"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
sha1 = "0.10.5"
sha3 = "0.10.6"
thiserror = "1.0.39"
tokio = { version = "1.26", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.4", features = ["full"] }
url = { version = "2.3", features = ["serde"] }

[dev-dependencies]
tokio = { version = "*", features = ["test-util"] }

[features]
default = [ "net-tests" ]
# If not enabled, will disable all network-related tests
net-tests = []