{{- if and .Values.secretKey (not .Values.secretKeyExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "camoflage.fullname" . }}-secret
  labels:
    {{- include "camoflage.labels" . | nindent 4 }}
type: Opaque
stringData:
  CAMO_SECRET_KEY: {{ .Values.secretKey | quote }}
  {{- if .Values.signRequestKey }}
  CAMO_SIGN_REQUEST_KEY: {{ .Values.signRequestKey | quote }}
  {{- end }}
{{- end }}
